// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package user

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UpsertResponse struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Status               string   `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Id                   string   `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	Matched              int64    `protobuf:"varint,4,opt,name=matched,proto3" json:"matched,omitempty"`
	Modified             int64    `protobuf:"varint,5,opt,name=modified,proto3" json:"modified,omitempty"`
	Token                string   `protobuf:"bytes,6,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpsertResponse) Reset()         { *m = UpsertResponse{} }
func (m *UpsertResponse) String() string { return proto.CompactTextString(m) }
func (*UpsertResponse) ProtoMessage()    {}
func (*UpsertResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *UpsertResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpsertResponse.Unmarshal(m, b)
}
func (m *UpsertResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpsertResponse.Marshal(b, m, deterministic)
}
func (m *UpsertResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpsertResponse.Merge(m, src)
}
func (m *UpsertResponse) XXX_Size() int {
	return xxx_messageInfo_UpsertResponse.Size(m)
}
func (m *UpsertResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpsertResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpsertResponse proto.InternalMessageInfo

func (m *UpsertResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *UpsertResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *UpsertResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpsertResponse) GetMatched() int64 {
	if m != nil {
		return m.Matched
	}
	return 0
}

func (m *UpsertResponse) GetModified() int64 {
	if m != nil {
		return m.Modified
	}
	return 0
}

func (m *UpsertResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type AuthResponse struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	User                 *User    `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	Status               string   `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthResponse) Reset()         { *m = AuthResponse{} }
func (m *AuthResponse) String() string { return proto.CompactTextString(m) }
func (*AuthResponse) ProtoMessage()    {}
func (*AuthResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}

func (m *AuthResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthResponse.Unmarshal(m, b)
}
func (m *AuthResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthResponse.Marshal(b, m, deterministic)
}
func (m *AuthResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthResponse.Merge(m, src)
}
func (m *AuthResponse) XXX_Size() int {
	return xxx_messageInfo_AuthResponse.Size(m)
}
func (m *AuthResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AuthResponse proto.InternalMessageInfo

func (m *AuthResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *AuthResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *AuthResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type UpsertRequest struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	User                 *User    `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	Id                   string   `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	Email                string   `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpsertRequest) Reset()         { *m = UpsertRequest{} }
func (m *UpsertRequest) String() string { return proto.CompactTextString(m) }
func (*UpsertRequest) ProtoMessage()    {}
func (*UpsertRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{2}
}

func (m *UpsertRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpsertRequest.Unmarshal(m, b)
}
func (m *UpsertRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpsertRequest.Marshal(b, m, deterministic)
}
func (m *UpsertRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpsertRequest.Merge(m, src)
}
func (m *UpsertRequest) XXX_Size() int {
	return xxx_messageInfo_UpsertRequest.Size(m)
}
func (m *UpsertRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpsertRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpsertRequest proto.InternalMessageInfo

func (m *UpsertRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *UpsertRequest) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *UpsertRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpsertRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UpsertRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type FindResponse struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Users                []*User  `protobuf:"bytes,2,rep,name=users,proto3" json:"users,omitempty"`
	Status               string   `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	User                 *User    `protobuf:"bytes,4,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindResponse) Reset()         { *m = FindResponse{} }
func (m *FindResponse) String() string { return proto.CompactTextString(m) }
func (*FindResponse) ProtoMessage()    {}
func (*FindResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{3}
}

func (m *FindResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindResponse.Unmarshal(m, b)
}
func (m *FindResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindResponse.Marshal(b, m, deterministic)
}
func (m *FindResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindResponse.Merge(m, src)
}
func (m *FindResponse) XXX_Size() int {
	return xxx_messageInfo_FindResponse.Size(m)
}
func (m *FindResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FindResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FindResponse proto.InternalMessageInfo

func (m *FindResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *FindResponse) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

func (m *FindResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *FindResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type FindRequest struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Language             string   `protobuf:"bytes,3,opt,name=language,proto3" json:"language,omitempty"`
	Experience           string   `protobuf:"bytes,4,opt,name=experience,proto3" json:"experience,omitempty"`
	Page                 int32    `protobuf:"varint,5,opt,name=page,proto3" json:"page,omitempty"`
	Limit                int32    `protobuf:"varint,6,opt,name=limit,proto3" json:"limit,omitempty"`
	Email                string   `protobuf:"bytes,7,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindRequest) Reset()         { *m = FindRequest{} }
func (m *FindRequest) String() string { return proto.CompactTextString(m) }
func (*FindRequest) ProtoMessage()    {}
func (*FindRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{4}
}

func (m *FindRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindRequest.Unmarshal(m, b)
}
func (m *FindRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindRequest.Marshal(b, m, deterministic)
}
func (m *FindRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindRequest.Merge(m, src)
}
func (m *FindRequest) XXX_Size() int {
	return xxx_messageInfo_FindRequest.Size(m)
}
func (m *FindRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FindRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FindRequest proto.InternalMessageInfo

func (m *FindRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *FindRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *FindRequest) GetLanguage() string {
	if m != nil {
		return m.Language
	}
	return ""
}

func (m *FindRequest) GetExperience() string {
	if m != nil {
		return m.Experience
	}
	return ""
}

func (m *FindRequest) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *FindRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *FindRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type DeleteResponse struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Status               string   `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Count                int64    `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteResponse) Reset()         { *m = DeleteResponse{} }
func (m *DeleteResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteResponse) ProtoMessage()    {}
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{5}
}

func (m *DeleteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteResponse.Unmarshal(m, b)
}
func (m *DeleteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteResponse.Marshal(b, m, deterministic)
}
func (m *DeleteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteResponse.Merge(m, src)
}
func (m *DeleteResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteResponse.Size(m)
}
func (m *DeleteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteResponse proto.InternalMessageInfo

func (m *DeleteResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *DeleteResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *DeleteResponse) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type DeleteRequest struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRequest) Reset()         { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()    {}
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{6}
}

func (m *DeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRequest.Unmarshal(m, b)
}
func (m *DeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRequest.Marshal(b, m, deterministic)
}
func (m *DeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRequest.Merge(m, src)
}
func (m *DeleteRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRequest.Size(m)
}
func (m *DeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRequest proto.InternalMessageInfo

func (m *DeleteRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *DeleteRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type ValidateResponse struct {
	Valid                bool     `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	UserId               string   `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ValidateResponse) Reset()         { *m = ValidateResponse{} }
func (m *ValidateResponse) String() string { return proto.CompactTextString(m) }
func (*ValidateResponse) ProtoMessage()    {}
func (*ValidateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{7}
}

func (m *ValidateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidateResponse.Unmarshal(m, b)
}
func (m *ValidateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidateResponse.Marshal(b, m, deterministic)
}
func (m *ValidateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidateResponse.Merge(m, src)
}
func (m *ValidateResponse) XXX_Size() int {
	return xxx_messageInfo_ValidateResponse.Size(m)
}
func (m *ValidateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ValidateResponse proto.InternalMessageInfo

func (m *ValidateResponse) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

func (m *ValidateResponse) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type ValidateRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ValidateRequest) Reset()         { *m = ValidateRequest{} }
func (m *ValidateRequest) String() string { return proto.CompactTextString(m) }
func (*ValidateRequest) ProtoMessage()    {}
func (*ValidateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{8}
}

func (m *ValidateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidateRequest.Unmarshal(m, b)
}
func (m *ValidateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidateRequest.Marshal(b, m, deterministic)
}
func (m *ValidateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidateRequest.Merge(m, src)
}
func (m *ValidateRequest) XXX_Size() int {
	return xxx_messageInfo_ValidateRequest.Size(m)
}
func (m *ValidateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ValidateRequest proto.InternalMessageInfo

func (m *ValidateRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type User struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Username             string   `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	LastActive           int32    `protobuf:"varint,4,opt,name=last_active,json=lastActive,proto3" json:"last_active,omitempty"`
	Experience           string   `protobuf:"bytes,5,opt,name=experience,proto3" json:"experience,omitempty"`
	Languages            []string `protobuf:"bytes,6,rep,name=languages,proto3" json:"languages,omitempty"`
	Id                   string   `protobuf:"bytes,7,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{9}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *User) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *User) GetLastActive() int32 {
	if m != nil {
		return m.LastActive
	}
	return 0
}

func (m *User) GetExperience() string {
	if m != nil {
		return m.Experience
	}
	return ""
}

func (m *User) GetLanguages() []string {
	if m != nil {
		return m.Languages
	}
	return nil
}

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func init() {
	proto.RegisterType((*UpsertResponse)(nil), "user.UpsertResponse")
	proto.RegisterType((*AuthResponse)(nil), "user.AuthResponse")
	proto.RegisterType((*UpsertRequest)(nil), "user.UpsertRequest")
	proto.RegisterType((*FindResponse)(nil), "user.FindResponse")
	proto.RegisterType((*FindRequest)(nil), "user.FindRequest")
	proto.RegisterType((*DeleteResponse)(nil), "user.DeleteResponse")
	proto.RegisterType((*DeleteRequest)(nil), "user.DeleteRequest")
	proto.RegisterType((*ValidateResponse)(nil), "user.ValidateResponse")
	proto.RegisterType((*ValidateRequest)(nil), "user.ValidateRequest")
	proto.RegisterType((*User)(nil), "user.User")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf) }

var fileDescriptor_116e343673f7ffaf = []byte{
	// 886 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x55, 0xd1, 0x72, 0xdb, 0x44,
	0x17, 0xfe, 0x25, 0x59, 0x76, 0x7c, 0x92, 0xb8, 0xfe, 0xb7, 0x6e, 0x30, 0x9e, 0x4e, 0xd1, 0x08,
	0x66, 0x9a, 0xc9, 0x10, 0xab, 0x09, 0xed, 0x4d, 0xae, 0x9a, 0xb6, 0x40, 0x3b, 0x30, 0xc0, 0x08,
	0xc2, 0xf4, 0xae, 0xb3, 0x96, 0x0e, 0xf2, 0x52, 0x79, 0x57, 0x68, 0x57, 0x4e, 0x0b, 0xc3, 0x0d,
	0xbc, 0x01, 0xcc, 0x70, 0xc1, 0x25, 0xb7, 0x3c, 0x01, 0x17, 0x5c, 0xf1, 0x08, 0xbc, 0x02, 0x0f,
	0xc2, 0xec, 0xae, 0xe5, 0xc8, 0x4e, 0xd3, 0x09, 0xb9, 0x92, 0xbe, 0xa3, 0x3d, 0xdf, 0x9e, 0xef,
	0x3b, 0x67, 0x57, 0x00, 0x95, 0xc4, 0x72, 0x5c, 0x94, 0x42, 0x09, 0xd2, 0xd2, 0xef, 0xa3, 0x9b,
	0x99, 0x10, 0x59, 0x8e, 0x11, 0x2d, 0x58, 0x44, 0x39, 0x17, 0x8a, 0x2a, 0x26, 0xb8, 0xb4, 0x6b,
	0x46, 0xef, 0x9a, 0x47, 0xb2, 0x9f, 0x21, 0xdf, 0x97, 0xa7, 0x34, 0xcb, 0xb0, 0x8c, 0x44, 0x61,
	0x56, 0x9c, 0x5f, 0x1d, 0xfe, 0xe2, 0x40, 0xef, 0xa4, 0x90, 0x58, 0xaa, 0x18, 0x65, 0x21, 0xb8,
	0x44, 0xd2, 0x07, 0x8f, 0x16, 0x6c, 0xe8, 0x04, 0xce, 0x6e, 0x37, 0xd6, 0xaf, 0x64, 0x07, 0xda,
	0x52, 0x51, 0x55, 0xc9, 0xa1, 0x6b, 0x82, 0x0b, 0x44, 0x7a, 0xe0, 0xb2, 0x74, 0xe8, 0x99, 0x98,
	0xcb, 0x52, 0x32, 0x84, 0xce, 0x8c, 0xaa, 0x64, 0x8a, 0xe9, 0xb0, 0x15, 0x38, 0xbb, 0x5e, 0x5c,
	0x43, 0x32, 0x82, 0x8d, 0x99, 0x48, 0xd9, 0x57, 0x0c, 0xd3, 0xa1, 0x6f, 0x3e, 0x2d, 0x31, 0x19,
	0x80, 0xaf, 0xc4, 0x73, 0xe4, 0xc3, 0xb6, 0x21, 0xb2, 0x20, 0x7c, 0x0a, 0x5b, 0xc7, 0x95, 0x9a,
	0xbe, 0xa6, 0xaa, 0x5b, 0x60, 0xec, 0x30, 0x35, 0x6d, 0x1e, 0xc2, 0xd8, 0xf8, 0x74, 0x22, 0xb1,
	0x8c, 0x4d, 0xbc, 0x51, 0xb5, 0xd7, 0xac, 0x3a, 0xfc, 0xd1, 0x81, 0xed, 0x5a, 0xf2, 0x37, 0x15,
	0x4a, 0x75, 0x05, 0xee, 0x75, 0xe5, 0x03, 0xf0, 0x71, 0x46, 0x59, 0x6e, 0x74, 0x77, 0x63, 0x0b,
	0xb4, 0xea, 0x82, 0x4a, 0x79, 0x2a, 0x4a, 0xab, 0xba, 0x1b, 0x2f, 0x71, 0xf8, 0x2d, 0x6c, 0x7d,
	0xc0, 0x78, 0xfa, 0x1a, 0x7d, 0x01, 0xf8, 0x7a, 0x2f, 0x6d, 0xba, 0xb7, 0x56, 0x84, 0xfd, 0x70,
	0x91, 0xc2, 0x65, 0xf5, 0xad, 0x57, 0x57, 0x1f, 0xfe, 0xee, 0xc0, 0xa6, 0xdd, 0xfc, 0x22, 0xfd,
	0x56, 0x9f, 0xbb, 0xd4, 0x37, 0x82, 0x8d, 0x9c, 0xf2, 0xac, 0xa2, 0x19, 0x2e, 0xf6, 0x5a, 0x62,
	0x72, 0x0b, 0x00, 0x5f, 0x14, 0x58, 0x32, 0xe4, 0x09, 0x2e, 0x0c, 0x68, 0x44, 0x08, 0x81, 0x56,
	0xa1, 0xf3, 0xb4, 0x03, 0x7e, 0x6c, 0xde, 0xb5, 0x5f, 0x39, 0x9b, 0x31, 0x65, 0x7a, 0xee, 0xc7,
	0x16, 0x9c, 0xb9, 0xd8, 0x69, 0xb8, 0x18, 0x7e, 0x06, 0xbd, 0x47, 0x98, 0xa3, 0xc2, 0x2b, 0x4c,
	0xe8, 0x00, 0xfc, 0x44, 0x54, 0x5c, 0x99, 0xa2, 0xbd, 0xd8, 0x82, 0xf0, 0x00, 0xb6, 0x6b, 0xc6,
	0x4b, 0x1a, 0x10, 0x1e, 0x43, 0xff, 0x4b, 0x9a, 0xb3, 0x94, 0x36, 0xca, 0x18, 0x80, 0x3f, 0xd7,
	0x31, 0x93, 0xb7, 0x11, 0x5b, 0x40, 0xde, 0x80, 0x8e, 0x36, 0xf9, 0xd9, 0x32, 0xbd, 0xad, 0xe1,
	0x93, 0x34, 0xbc, 0x0d, 0xd7, 0xce, 0x28, 0xec, 0xbe, 0xcb, 0xd1, 0x77, 0x9a, 0xa3, 0xff, 0x97,
	0x03, 0x2d, 0xdd, 0xad, 0x33, 0x3f, 0x9c, 0x8b, 0xa6, 0xca, 0x5d, 0x9d, 0x2a, 0xfd, 0x4d, 0xef,
	0xc6, 0xe9, 0x6c, 0xd9, 0xa7, 0x1a, 0x93, 0xb7, 0x60, 0x33, 0xa7, 0x52, 0x3d, 0xa3, 0x89, 0x62,
	0x73, 0xdb, 0x28, 0x3f, 0x06, 0x1d, 0x3a, 0x36, 0x91, 0xb5, 0x46, 0xfa, 0xe7, 0x1a, 0x79, 0x13,
	0xba, 0x75, 0xd3, 0xe5, 0xb0, 0x1d, 0x78, 0xbb, 0xdd, 0xf8, 0x2c, 0xb0, 0x70, 0xac, 0x53, 0x3b,
	0x76, 0xf8, 0x9b, 0x0f, 0x9b, 0x5a, 0xc5, 0xe7, 0x58, 0xce, 0x59, 0x82, 0xe4, 0x13, 0x80, 0x87,
	0x25, 0x52, 0x85, 0x46, 0xda, 0xf5, 0xc5, 0x50, 0x36, 0xcf, 0xe1, 0x68, 0xb0, 0x1a, 0xb4, 0x36,
	0x87, 0x37, 0x7e, 0xf8, 0xfb, 0x9f, 0x9f, 0xdd, 0x6b, 0x21, 0x44, 0xf3, 0x83, 0x48, 0xb2, 0x8c,
	0x57, 0xc5, 0x91, 0xb3, 0x47, 0x1e, 0x41, 0xe7, 0x43, 0x54, 0xfa, 0x8e, 0x78, 0x35, 0x19, 0xb1,
	0xc1, 0xe6, 0x25, 0x12, 0xf6, 0x0d, 0x15, 0x90, 0x0d, 0x4d, 0x45, 0x75, 0xea, 0x63, 0xf0, 0x3f,
	0x16, 0x19, 0xe3, 0xff, 0xa5, 0xa0, 0x81, 0x61, 0xe9, 0x85, 0x5d, 0xcd, 0x92, 0xeb, 0x6c, 0x5d,
	0x4f, 0x0c, 0x70, 0x52, 0xa4, 0x57, 0xd0, 0xf7, 0xa6, 0xa1, 0xbb, 0x1e, 0xf6, 0x34, 0x9d, 0x39,
	0xd8, 0xd1, 0x77, 0x2c, 0xfd, 0x5e, 0x73, 0x7e, 0x0a, 0x60, 0x07, 0xb5, 0xc9, 0xb9, 0x32, 0xba,
	0x35, 0xe7, 0xea, 0x09, 0x09, 0x77, 0x0c, 0x67, 0x7f, 0x6f, 0x8d, 0x93, 0x3c, 0x36, 0xa6, 0x3d,
	0x78, 0xf9, 0x24, 0x25, 0xff, 0xb7, 0x89, 0x8d, 0x7b, 0xa0, 0xb6, 0xac, 0x79, 0x2f, 0xd5, 0x4c,
	0x64, 0x9d, 0xe9, 0x1e, 0x80, 0x61, 0x7a, 0xdf, 0xcc, 0xe4, 0x25, 0xc9, 0xfe, 0x47, 0x3e, 0xd2,
	0x37, 0x4f, 0xae, 0xb0, 0x3c, 0x31, 0x37, 0xd8, 0x25, 0xf3, 0x56, 0x47, 0x00, 0x69, 0x99, 0x4c,
	0xb5, 0x3d, 0xf7, 0x61, 0xbb, 0x3e, 0x51, 0x5f, 0xe8, 0x93, 0x43, 0x6e, 0xd8, 0xdc, 0xb5, 0x63,
	0x36, 0xda, 0x59, 0x0f, 0xd7, 0xe5, 0x3c, 0xf8, 0xd3, 0xf9, 0xe9, 0xf8, 0x0f, 0x87, 0x3c, 0x85,
	0x2d, 0xbd, 0x22, 0x90, 0x76, 0x56, 0xc3, 0x87, 0xab, 0x98, 0xbc, 0x3d, 0x55, 0xaa, 0x90, 0x47,
	0x51, 0x94, 0x31, 0x35, 0xad, 0x26, 0xe3, 0x44, 0xcc, 0xa2, 0xe4, 0xf9, 0x64, 0x42, 0xf3, 0x3c,
	0x4a, 0x71, 0xbe, 0x6f, 0x7e, 0xcb, 0xbd, 0x49, 0x4e, 0xa7, 0xf7, 0xa7, 0xb4, 0x28, 0x5e, 0x8e,
	0x45, 0x99, 0x1d, 0x7a, 0x07, 0xe3, 0x3b, 0x7b, 0xae, 0xe3, 0x1e, 0xf6, 0x69, 0x51, 0xe4, 0x2c,
	0x31, 0xff, 0xdd, 0xe8, 0x6b, 0x29, 0xf8, 0xd1, 0xb9, 0x48, 0x7c, 0x0f, 0xbc, 0xbb, 0x77, 0xee,
	0x92, 0x31, 0xbc, 0x13, 0xa3, 0xaa, 0x4a, 0x8e, 0x69, 0x70, 0x3a, 0x45, 0x1e, 0x94, 0x28, 0x45,
	0x55, 0x26, 0x18, 0xa4, 0x02, 0x25, 0xbf, 0xad, 0x02, 0x7c, 0xc1, 0xa4, 0x22, 0x6d, 0x68, 0xfd,
	0xea, 0x3a, 0x9d, 0x49, 0xdb, 0xfc, 0xc5, 0xdf, 0xfb, 0x37, 0x00, 0x00, 0xff, 0xff, 0xfa, 0x7f,
	0x4f, 0x6b, 0x25, 0x08, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserServiceClient interface {
	CreateUser(ctx context.Context, in *UpsertRequest, opts ...grpc.CallOption) (*UpsertResponse, error)
	GetAuth(ctx context.Context, in *UpsertRequest, opts ...grpc.CallOption) (*AuthResponse, error)
	Login(ctx context.Context, in *UpsertRequest, opts ...grpc.CallOption) (*UpsertResponse, error)
	UpdateUser(ctx context.Context, in *UpsertRequest, opts ...grpc.CallOption) (*UpsertResponse, error)
	DeleteUser(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
	GetById(ctx context.Context, in *FindRequest, opts ...grpc.CallOption) (*FindResponse, error)
	GetByEmail(ctx context.Context, in *FindRequest, opts ...grpc.CallOption) (*FindResponse, error)
	FilterUsers(ctx context.Context, in *FindRequest, opts ...grpc.CallOption) (*FindResponse, error)
	ValidateToken(ctx context.Context, in *ValidateRequest, opts ...grpc.CallOption) (*ValidateResponse, error)
}

type userServiceClient struct {
	cc *grpc.ClientConn
}

func NewUserServiceClient(cc *grpc.ClientConn) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) CreateUser(ctx context.Context, in *UpsertRequest, opts ...grpc.CallOption) (*UpsertResponse, error) {
	out := new(UpsertResponse)
	err := c.cc.Invoke(ctx, "/user.UserService/CreateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetAuth(ctx context.Context, in *UpsertRequest, opts ...grpc.CallOption) (*AuthResponse, error) {
	out := new(AuthResponse)
	err := c.cc.Invoke(ctx, "/user.UserService/GetAuth", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) Login(ctx context.Context, in *UpsertRequest, opts ...grpc.CallOption) (*UpsertResponse, error) {
	out := new(UpsertResponse)
	err := c.cc.Invoke(ctx, "/user.UserService/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) UpdateUser(ctx context.Context, in *UpsertRequest, opts ...grpc.CallOption) (*UpsertResponse, error) {
	out := new(UpsertResponse)
	err := c.cc.Invoke(ctx, "/user.UserService/UpdateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) DeleteUser(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, "/user.UserService/DeleteUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetById(ctx context.Context, in *FindRequest, opts ...grpc.CallOption) (*FindResponse, error) {
	out := new(FindResponse)
	err := c.cc.Invoke(ctx, "/user.UserService/GetById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetByEmail(ctx context.Context, in *FindRequest, opts ...grpc.CallOption) (*FindResponse, error) {
	out := new(FindResponse)
	err := c.cc.Invoke(ctx, "/user.UserService/GetByEmail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) FilterUsers(ctx context.Context, in *FindRequest, opts ...grpc.CallOption) (*FindResponse, error) {
	out := new(FindResponse)
	err := c.cc.Invoke(ctx, "/user.UserService/FilterUsers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) ValidateToken(ctx context.Context, in *ValidateRequest, opts ...grpc.CallOption) (*ValidateResponse, error) {
	out := new(ValidateResponse)
	err := c.cc.Invoke(ctx, "/user.UserService/ValidateToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
type UserServiceServer interface {
	CreateUser(context.Context, *UpsertRequest) (*UpsertResponse, error)
	GetAuth(context.Context, *UpsertRequest) (*AuthResponse, error)
	Login(context.Context, *UpsertRequest) (*UpsertResponse, error)
	UpdateUser(context.Context, *UpsertRequest) (*UpsertResponse, error)
	DeleteUser(context.Context, *DeleteRequest) (*DeleteResponse, error)
	GetById(context.Context, *FindRequest) (*FindResponse, error)
	GetByEmail(context.Context, *FindRequest) (*FindResponse, error)
	FilterUsers(context.Context, *FindRequest) (*FindResponse, error)
	ValidateToken(context.Context, *ValidateRequest) (*ValidateResponse, error)
}

// UnimplementedUserServiceServer can be embedded to have forward compatible implementations.
type UnimplementedUserServiceServer struct {
}

func (*UnimplementedUserServiceServer) CreateUser(ctx context.Context, req *UpsertRequest) (*UpsertResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUser not implemented")
}
func (*UnimplementedUserServiceServer) GetAuth(ctx context.Context, req *UpsertRequest) (*AuthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAuth not implemented")
}
func (*UnimplementedUserServiceServer) Login(ctx context.Context, req *UpsertRequest) (*UpsertResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (*UnimplementedUserServiceServer) UpdateUser(ctx context.Context, req *UpsertRequest) (*UpsertResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateUser not implemented")
}
func (*UnimplementedUserServiceServer) DeleteUser(ctx context.Context, req *DeleteRequest) (*DeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteUser not implemented")
}
func (*UnimplementedUserServiceServer) GetById(ctx context.Context, req *FindRequest) (*FindResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetById not implemented")
}
func (*UnimplementedUserServiceServer) GetByEmail(ctx context.Context, req *FindRequest) (*FindResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetByEmail not implemented")
}
func (*UnimplementedUserServiceServer) FilterUsers(ctx context.Context, req *FindRequest) (*FindResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FilterUsers not implemented")
}
func (*UnimplementedUserServiceServer) ValidateToken(ctx context.Context, req *ValidateRequest) (*ValidateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidateToken not implemented")
}

func RegisterUserServiceServer(s *grpc.Server, srv UserServiceServer) {
	s.RegisterService(&_UserService_serviceDesc, srv)
}

func _UserService_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/CreateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).CreateUser(ctx, req.(*UpsertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetAuth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetAuth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/GetAuth",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetAuth(ctx, req.(*UpsertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).Login(ctx, req.(*UpsertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_UpdateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).UpdateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/UpdateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).UpdateUser(ctx, req.(*UpsertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_DeleteUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).DeleteUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/DeleteUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).DeleteUser(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/GetById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetById(ctx, req.(*FindRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetByEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetByEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/GetByEmail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetByEmail(ctx, req.(*FindRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_FilterUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).FilterUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/FilterUsers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).FilterUsers(ctx, req.(*FindRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_ValidateToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).ValidateToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/ValidateToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).ValidateToken(ctx, req.(*ValidateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "user.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUser",
			Handler:    _UserService_CreateUser_Handler,
		},
		{
			MethodName: "GetAuth",
			Handler:    _UserService_GetAuth_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _UserService_Login_Handler,
		},
		{
			MethodName: "UpdateUser",
			Handler:    _UserService_UpdateUser_Handler,
		},
		{
			MethodName: "DeleteUser",
			Handler:    _UserService_DeleteUser_Handler,
		},
		{
			MethodName: "GetById",
			Handler:    _UserService_GetById_Handler,
		},
		{
			MethodName: "GetByEmail",
			Handler:    _UserService_GetByEmail_Handler,
		},
		{
			MethodName: "FilterUsers",
			Handler:    _UserService_FilterUsers_Handler,
		},
		{
			MethodName: "ValidateToken",
			Handler:    _UserService_ValidateToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user.proto",
}
