// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package user

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UpsertResponse struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Status               string   `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Id                   string   `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	Matched              string   `protobuf:"bytes,4,opt,name=matched,proto3" json:"matched,omitempty"`
	Modified             string   `protobuf:"bytes,5,opt,name=modified,proto3" json:"modified,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpsertResponse) Reset()         { *m = UpsertResponse{} }
func (m *UpsertResponse) String() string { return proto.CompactTextString(m) }
func (*UpsertResponse) ProtoMessage()    {}
func (*UpsertResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *UpsertResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpsertResponse.Unmarshal(m, b)
}
func (m *UpsertResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpsertResponse.Marshal(b, m, deterministic)
}
func (m *UpsertResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpsertResponse.Merge(m, src)
}
func (m *UpsertResponse) XXX_Size() int {
	return xxx_messageInfo_UpsertResponse.Size(m)
}
func (m *UpsertResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpsertResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpsertResponse proto.InternalMessageInfo

func (m *UpsertResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *UpsertResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *UpsertResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpsertResponse) GetMatched() string {
	if m != nil {
		return m.Matched
	}
	return ""
}

func (m *UpsertResponse) GetModified() string {
	if m != nil {
		return m.Modified
	}
	return ""
}

type UpsertRequest struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	User                 *User    `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	Id                   string   `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpsertRequest) Reset()         { *m = UpsertRequest{} }
func (m *UpsertRequest) String() string { return proto.CompactTextString(m) }
func (*UpsertRequest) ProtoMessage()    {}
func (*UpsertRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}

func (m *UpsertRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpsertRequest.Unmarshal(m, b)
}
func (m *UpsertRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpsertRequest.Marshal(b, m, deterministic)
}
func (m *UpsertRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpsertRequest.Merge(m, src)
}
func (m *UpsertRequest) XXX_Size() int {
	return xxx_messageInfo_UpsertRequest.Size(m)
}
func (m *UpsertRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpsertRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpsertRequest proto.InternalMessageInfo

func (m *UpsertRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *UpsertRequest) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *UpsertRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type FindResponse struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Users                []*User  `protobuf:"bytes,2,rep,name=users,proto3" json:"users,omitempty"`
	Status               string   `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindResponse) Reset()         { *m = FindResponse{} }
func (m *FindResponse) String() string { return proto.CompactTextString(m) }
func (*FindResponse) ProtoMessage()    {}
func (*FindResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{2}
}

func (m *FindResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindResponse.Unmarshal(m, b)
}
func (m *FindResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindResponse.Marshal(b, m, deterministic)
}
func (m *FindResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindResponse.Merge(m, src)
}
func (m *FindResponse) XXX_Size() int {
	return xxx_messageInfo_FindResponse.Size(m)
}
func (m *FindResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FindResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FindResponse proto.InternalMessageInfo

func (m *FindResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *FindResponse) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

func (m *FindResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type FindRequest struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Language             string   `protobuf:"bytes,3,opt,name=language,proto3" json:"language,omitempty"`
	Experience           string   `protobuf:"bytes,4,opt,name=experience,proto3" json:"experience,omitempty"`
	Page                 int32    `protobuf:"varint,5,opt,name=page,proto3" json:"page,omitempty"`
	Limit                int32    `protobuf:"varint,6,opt,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindRequest) Reset()         { *m = FindRequest{} }
func (m *FindRequest) String() string { return proto.CompactTextString(m) }
func (*FindRequest) ProtoMessage()    {}
func (*FindRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{3}
}

func (m *FindRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindRequest.Unmarshal(m, b)
}
func (m *FindRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindRequest.Marshal(b, m, deterministic)
}
func (m *FindRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindRequest.Merge(m, src)
}
func (m *FindRequest) XXX_Size() int {
	return xxx_messageInfo_FindRequest.Size(m)
}
func (m *FindRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FindRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FindRequest proto.InternalMessageInfo

func (m *FindRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *FindRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *FindRequest) GetLanguage() string {
	if m != nil {
		return m.Language
	}
	return ""
}

func (m *FindRequest) GetExperience() string {
	if m != nil {
		return m.Experience
	}
	return ""
}

func (m *FindRequest) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *FindRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type DeleteResponse struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Status               string   `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteResponse) Reset()         { *m = DeleteResponse{} }
func (m *DeleteResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteResponse) ProtoMessage()    {}
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{4}
}

func (m *DeleteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteResponse.Unmarshal(m, b)
}
func (m *DeleteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteResponse.Marshal(b, m, deterministic)
}
func (m *DeleteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteResponse.Merge(m, src)
}
func (m *DeleteResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteResponse.Size(m)
}
func (m *DeleteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteResponse proto.InternalMessageInfo

func (m *DeleteResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *DeleteResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type DeleteRequest struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRequest) Reset()         { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()    {}
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{5}
}

func (m *DeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRequest.Unmarshal(m, b)
}
func (m *DeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRequest.Marshal(b, m, deterministic)
}
func (m *DeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRequest.Merge(m, src)
}
func (m *DeleteRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRequest.Size(m)
}
func (m *DeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRequest proto.InternalMessageInfo

func (m *DeleteRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *DeleteRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type User struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Username             string   `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	LastActive           int32    `protobuf:"varint,4,opt,name=last_active,json=lastActive,proto3" json:"last_active,omitempty"`
	Experience           string   `protobuf:"bytes,5,opt,name=experience,proto3" json:"experience,omitempty"`
	Languages            []string `protobuf:"bytes,6,rep,name=languages,proto3" json:"languages,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{6}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *User) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *User) GetLastActive() int32 {
	if m != nil {
		return m.LastActive
	}
	return 0
}

func (m *User) GetExperience() string {
	if m != nil {
		return m.Experience
	}
	return ""
}

func (m *User) GetLanguages() []string {
	if m != nil {
		return m.Languages
	}
	return nil
}

func init() {
	proto.RegisterType((*UpsertResponse)(nil), "user.UpsertResponse")
	proto.RegisterType((*UpsertRequest)(nil), "user.UpsertRequest")
	proto.RegisterType((*FindResponse)(nil), "user.FindResponse")
	proto.RegisterType((*FindRequest)(nil), "user.FindRequest")
	proto.RegisterType((*DeleteResponse)(nil), "user.DeleteResponse")
	proto.RegisterType((*DeleteRequest)(nil), "user.DeleteRequest")
	proto.RegisterType((*User)(nil), "user.User")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf) }

var fileDescriptor_116e343673f7ffaf = []byte{
	// 698 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0xcd, 0x6e, 0xd3, 0x4c,
	0x14, 0x95, 0xed, 0x24, 0x6d, 0x6e, 0xda, 0x28, 0xdf, 0xb4, 0x5f, 0xe5, 0x2f, 0x5f, 0x55, 0x2c,
	0x0b, 0xa9, 0x55, 0x44, 0xe3, 0x36, 0x94, 0x4d, 0x56, 0xb4, 0x20, 0x0a, 0x0b, 0x84, 0x6a, 0x94,
	0x0d, 0x42, 0x42, 0x13, 0xfb, 0xd6, 0x19, 0x70, 0x6c, 0x33, 0x33, 0xee, 0x8f, 0x10, 0x12, 0xe2,
	0x11, 0x40, 0x6c, 0x58, 0xf0, 0x12, 0xac, 0x59, 0xf0, 0x0c, 0xbc, 0x02, 0x0f, 0x82, 0x66, 0x9c,
	0xa4, 0x49, 0x0a, 0xa8, 0xb0, 0xca, 0x9c, 0x33, 0x73, 0x4f, 0xee, 0x39, 0x77, 0x3c, 0x00, 0xb9,
	0x40, 0xde, 0xce, 0x78, 0x2a, 0x53, 0x52, 0x52, 0xeb, 0xe6, 0x7a, 0x94, 0xa6, 0x51, 0x8c, 0x1e,
	0xcd, 0x98, 0x47, 0x93, 0x24, 0x95, 0x54, 0xb2, 0x34, 0x11, 0xc5, 0x99, 0xe6, 0x0d, 0xfd, 0x13,
	0x6c, 0x47, 0x98, 0x6c, 0x8b, 0x53, 0x1a, 0x45, 0xc8, 0xbd, 0x34, 0xd3, 0x27, 0x2e, 0x9f, 0x76,
	0xdf, 0x18, 0x50, 0xef, 0x65, 0x02, 0xb9, 0xf4, 0x51, 0x64, 0x69, 0x22, 0x90, 0x34, 0xc0, 0xa2,
	0x19, 0xb3, 0x0d, 0xc7, 0xd8, 0xaa, 0xfa, 0x6a, 0x49, 0xd6, 0xa0, 0x22, 0x24, 0x95, 0xb9, 0xb0,
	0x4d, 0x4d, 0x8e, 0x10, 0xa9, 0x83, 0xc9, 0x42, 0xdb, 0xd2, 0x9c, 0xc9, 0x42, 0x62, 0xc3, 0xc2,
	0x90, 0xca, 0x60, 0x80, 0xa1, 0x5d, 0xd2, 0xe4, 0x18, 0x92, 0x26, 0x2c, 0x0e, 0xd3, 0x90, 0x1d,
	0x33, 0x0c, 0xed, 0xb2, 0xde, 0x9a, 0x60, 0xf7, 0x08, 0x96, 0xc7, 0x1d, 0xbc, 0xcc, 0x51, 0xc8,
	0x9f, 0x34, 0xb0, 0x01, 0xda, 0xb9, 0xfe, 0xfb, 0x5a, 0x07, 0xda, 0x3a, 0x92, 0x9e, 0x40, 0xee,
	0x6b, 0x7e, 0xbe, 0x11, 0xf7, 0x09, 0x2c, 0xdd, 0x63, 0x49, 0xf8, 0x1b, 0x4b, 0x0e, 0x94, 0x55,
	0xa5, 0x72, 0x64, 0xcd, 0x49, 0x16, 0x1b, 0x53, 0xa6, 0xad, 0x69, 0xd3, 0xee, 0x07, 0x03, 0x6a,
	0x85, 0xf8, 0xaf, 0xba, 0x2d, 0xba, 0x31, 0x27, 0xb1, 0x34, 0x61, 0x31, 0xa6, 0x49, 0x94, 0xd3,
	0x08, 0x47, 0x5a, 0x13, 0x4c, 0x36, 0x00, 0xf0, 0x2c, 0x43, 0xce, 0x30, 0x09, 0x70, 0x94, 0xda,
	0x14, 0x43, 0x08, 0x94, 0x32, 0x55, 0xa7, 0x42, 0x2b, 0xfb, 0x7a, 0x4d, 0x56, 0xa1, 0x1c, 0xb3,
	0x21, 0x93, 0x76, 0x45, 0x93, 0x05, 0x70, 0xbb, 0x50, 0xbf, 0x8b, 0x31, 0x4a, 0xfc, 0xf3, 0x41,
	0xba, 0xbb, 0xb0, 0x3c, 0xae, 0xbd, 0xa2, 0x29, 0xf7, 0xb3, 0x01, 0x25, 0x15, 0x97, 0xea, 0x06,
	0x87, 0x94, 0xc5, 0xa3, 0xc3, 0x05, 0x50, 0x9e, 0x33, 0x2a, 0xc4, 0x69, 0xca, 0xc7, 0x45, 0x13,
	0xac, 0xf6, 0x54, 0xc4, 0x09, 0x1d, 0x4e, 0xf2, 0x18, 0x63, 0x72, 0x0d, 0x6a, 0x31, 0x15, 0xf2,
	0x19, 0x0d, 0x24, 0x3b, 0x29, 0x02, 0x29, 0xfb, 0xa0, 0xa8, 0x7d, 0xcd, 0xcc, 0x05, 0x56, 0xbe,
	0x14, 0xd8, 0x3a, 0x54, 0xc7, 0xe1, 0x0a, 0xbb, 0xe2, 0x58, 0x5b, 0x55, 0xff, 0x82, 0xe8, 0x7c,
	0xb2, 0xa0, 0xa6, 0xba, 0x7e, 0x8c, 0xfc, 0x84, 0x05, 0x48, 0x1e, 0x02, 0xdc, 0xe1, 0x48, 0x25,
	0x6a, 0x2b, 0x2b, 0xa3, 0x5b, 0x30, 0x7d, 0x1b, 0x9b, 0xab, 0xb3, 0x64, 0x91, 0xad, 0xbb, 0xfa,
	0xf6, 0xdb, 0xf7, 0xf7, 0x66, 0xdd, 0xad, 0x7a, 0x27, 0xbb, 0x9e, 0xbe, 0x30, 0x5d, 0xa3, 0x45,
	0x7c, 0x80, 0x5e, 0x16, 0xfe, 0x85, 0xdc, 0x7f, 0x5a, 0x6e, 0xc5, 0xad, 0x4f, 0xe4, 0xbc, 0x57,
	0x2c, 0x7c, 0xad, 0x34, 0x1f, 0x01, 0x14, 0xb3, 0x99, 0xd6, 0x9c, 0x99, 0xd6, 0x58, 0x73, 0x76,
	0xfc, 0xee, 0x9a, 0xd6, 0x6c, 0xb4, 0xe6, 0x34, 0xc9, 0x7d, 0x58, 0x38, 0x44, 0x79, 0x70, 0xfe,
	0x20, 0x24, 0xff, 0x14, 0x85, 0x53, 0xd7, 0xb9, 0x49, 0xa6, 0xa9, 0x59, 0x25, 0x32, 0xaf, 0x74,
	0xa4, 0xbe, 0x84, 0x58, 0x22, 0xef, 0xe9, 0x2f, 0xe6, 0x8a, 0x6a, 0xff, 0x6b, 0xb5, 0x7f, 0xdd,
	0xc6, 0x85, 0x9a, 0x40, 0xca, 0x83, 0x41, 0xd7, 0x68, 0x1d, 0x7c, 0x35, 0xde, 0xed, 0x7f, 0x31,
	0xc8, 0x53, 0x58, 0x52, 0x3b, 0x8e, 0x28, 0xe6, 0xe4, 0x1e, 0xce, 0x62, 0xb2, 0x39, 0x90, 0x32,
	0x13, 0x5d, 0xcf, 0x8b, 0x98, 0x1c, 0xe4, 0xfd, 0x76, 0x90, 0x0e, 0xbd, 0xe0, 0x45, 0xbf, 0x4f,
	0xe3, 0xd8, 0x13, 0xc3, 0x9c, 0x1f, 0xb3, 0x64, 0x5b, 0xbf, 0x95, 0xf5, 0x7e, 0x4c, 0x07, 0xb7,
	0x07, 0x34, 0xcb, 0xce, 0xdb, 0x29, 0x8f, 0x3a, 0xd6, 0x6e, 0x7b, 0xa7, 0x65, 0x1a, 0x66, 0xa7,
	0x41, 0xb3, 0x2c, 0x66, 0x81, 0x7e, 0x0c, 0xbd, 0xe7, 0x22, 0x4d, 0xba, 0x97, 0x18, 0xff, 0x16,
	0x58, 0x7b, 0x3b, 0x7b, 0xa4, 0x0d, 0xd7, 0x7d, 0x94, 0x39, 0x4f, 0x30, 0x74, 0x4e, 0x07, 0x98,
	0x38, 0x1c, 0x45, 0x9a, 0xf3, 0x00, 0x9d, 0x30, 0x45, 0x91, 0x6c, 0x4a, 0x07, 0xcf, 0x98, 0x90,
	0xa4, 0x02, 0xa5, 0x8f, 0xa6, 0xb1, 0xd0, 0xaf, 0xe8, 0xa7, 0xf5, 0xe6, 0x8f, 0x00, 0x00, 0x00,
	0xff, 0xff, 0xb1, 0xf6, 0x95, 0xa1, 0xba, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserServiceClient interface {
	CreateUser(ctx context.Context, in *UpsertRequest, opts ...grpc.CallOption) (*UpsertResponse, error)
	UpdateUser(ctx context.Context, in *UpsertRequest, opts ...grpc.CallOption) (*UpsertResponse, error)
	DeleteUser(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
	GetById(ctx context.Context, in *FindRequest, opts ...grpc.CallOption) (*FindResponse, error)
	FilterUsers(ctx context.Context, in *FindRequest, opts ...grpc.CallOption) (*FindResponse, error)
}

type userServiceClient struct {
	cc *grpc.ClientConn
}

func NewUserServiceClient(cc *grpc.ClientConn) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) CreateUser(ctx context.Context, in *UpsertRequest, opts ...grpc.CallOption) (*UpsertResponse, error) {
	out := new(UpsertResponse)
	err := c.cc.Invoke(ctx, "/user.UserService/CreateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) UpdateUser(ctx context.Context, in *UpsertRequest, opts ...grpc.CallOption) (*UpsertResponse, error) {
	out := new(UpsertResponse)
	err := c.cc.Invoke(ctx, "/user.UserService/UpdateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) DeleteUser(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, "/user.UserService/DeleteUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetById(ctx context.Context, in *FindRequest, opts ...grpc.CallOption) (*FindResponse, error) {
	out := new(FindResponse)
	err := c.cc.Invoke(ctx, "/user.UserService/GetById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) FilterUsers(ctx context.Context, in *FindRequest, opts ...grpc.CallOption) (*FindResponse, error) {
	out := new(FindResponse)
	err := c.cc.Invoke(ctx, "/user.UserService/FilterUsers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
type UserServiceServer interface {
	CreateUser(context.Context, *UpsertRequest) (*UpsertResponse, error)
	UpdateUser(context.Context, *UpsertRequest) (*UpsertResponse, error)
	DeleteUser(context.Context, *DeleteRequest) (*DeleteResponse, error)
	GetById(context.Context, *FindRequest) (*FindResponse, error)
	FilterUsers(context.Context, *FindRequest) (*FindResponse, error)
}

// UnimplementedUserServiceServer can be embedded to have forward compatible implementations.
type UnimplementedUserServiceServer struct {
}

func (*UnimplementedUserServiceServer) CreateUser(ctx context.Context, req *UpsertRequest) (*UpsertResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUser not implemented")
}
func (*UnimplementedUserServiceServer) UpdateUser(ctx context.Context, req *UpsertRequest) (*UpsertResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateUser not implemented")
}
func (*UnimplementedUserServiceServer) DeleteUser(ctx context.Context, req *DeleteRequest) (*DeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteUser not implemented")
}
func (*UnimplementedUserServiceServer) GetById(ctx context.Context, req *FindRequest) (*FindResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetById not implemented")
}
func (*UnimplementedUserServiceServer) FilterUsers(ctx context.Context, req *FindRequest) (*FindResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FilterUsers not implemented")
}

func RegisterUserServiceServer(s *grpc.Server, srv UserServiceServer) {
	s.RegisterService(&_UserService_serviceDesc, srv)
}

func _UserService_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/CreateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).CreateUser(ctx, req.(*UpsertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_UpdateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).UpdateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/UpdateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).UpdateUser(ctx, req.(*UpsertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_DeleteUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).DeleteUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/DeleteUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).DeleteUser(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/GetById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetById(ctx, req.(*FindRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_FilterUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).FilterUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/FilterUsers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).FilterUsers(ctx, req.(*FindRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "user.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUser",
			Handler:    _UserService_CreateUser_Handler,
		},
		{
			MethodName: "UpdateUser",
			Handler:    _UserService_UpdateUser_Handler,
		},
		{
			MethodName: "DeleteUser",
			Handler:    _UserService_DeleteUser_Handler,
		},
		{
			MethodName: "GetById",
			Handler:    _UserService_GetById_Handler,
		},
		{
			MethodName: "FilterUsers",
			Handler:    _UserService_FilterUsers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user.proto",
}
